name: CI (Front-end)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependências
        run: npm install

      - name: Gerar CSS de produção
        run: npm run build

      - name: Verificar arquivo principal
        run: |
          test -f index.html
          echo "index.html encontrado com sucesso"